{% set name = "symfem" %}
{% set version = "2025.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5d1df1ef947bd4116e5d0800723e8e693f452fc18a9a0d6d584e25eea7f99245

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit
  run:
    - python >={{ python_min }}
    - sympy
    - appdirs

test:
  requires:
    - python {{ python_min }}
  imports:
    - symfem

about:
  home: http://github.com/mscroggs/symfem
  license: MIT
  license_family: MIT

  license_file: LICENSE
  summary: A symbolic finite element definition library

  description: |
    Symfem is a symbolic finite element definition library, that can be used to
    symbolically evaluate the basis functions of a finite element space.
  dev_url: https://github.com/mscroggs/symfem

extra:
  recipe-maintainers:
    - mscroggs
