{% set name = "symfem" %}
{% set version = "2024.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6ea9301829eb922aa38507760d1121e1582a514edfa817c2e78b2a107264b713

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.7
    - pip
    - flit
  run:
    - python >=3.7
    - sympy
    - appdirs

test:
  imports:
    - symfem

about:
  home: http://github.com/mscroggs/symfem
  license: MIT
  license_family: MIT

  license_file: LICENSE
  summary: A symbolic finite element definition library

  description: |
    Symfem is a symbolic finite element definition library, that can be used to
    symbolically evaluate the basis functions of a finite element space.
  dev_url: https://github.com/mscroggs/symfem

extra:
  recipe-maintainers:
    - mscroggs
