{% set name = "symfem" %}
{% set version = "2022.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6641517bc7ed29e134240cfe128b2eecf65e1a1db83e1437bebe4b9812afff8b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - numpy
    - python >=3.7
    - sympy

test:
  imports:
    - symfem

about:
  home: http://github.com/mscroggs/symfem
  license: MIT
  license_family: MIT

  license_file: LICENSE
  summary: A symbolic finite element definition library

  description: |
    Symfem is a symbolic finite element definition library, that can be used to  
    symbolically evaluate the basis functions of a finite element space.
  dev_url: https://github.com/mscroggs/symfem

extra:
  recipe-maintainers:
    - mscroggs
