{% set name = "symfem" %}
{% set version = "2021.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6ad4197110e992a927fed0842ae46bea20157f251098c7c86fe0a244ab1887dc

build:
  noarch: python
  number: 0

  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - numpy
    - python >=3.6
    - sympy

test:
  imports:
    - symfem

about:
  home: http://github.com/mscroggs/symfem
  license: MIT
  license_family: MIT

  license_file: LICENSE
  summary: A symbolic finite element definition library

  description: |
    Symfem is a symbolic finite element definition library, that can be used to  
    symbolically evaluate the basis functions of a finite element space.
  dev_url: https://github.com/mscroggs/symfem

extra:
  recipe-maintainers:
    - mscroggs
