{% set name = "symfem" %}
{% set version = "2025.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d1adc109f930791c40894fa2ec3584d3ddaf6d5cf3b60d7dbf878ccca6301f13

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit
  run:
    - python >={{ python_min }}
    - sympy
    - appdirs

test:
  requires:
    - python {{ python_min }}
  imports:
    - symfem

about:
  home: http://github.com/mscroggs/symfem
  license: MIT
  license_family: MIT

  license_file: LICENSE
  summary: A symbolic finite element definition library

  description: |
    Symfem is a symbolic finite element definition library, that can be used to
    symbolically evaluate the basis functions of a finite element space.
  dev_url: https://github.com/mscroggs/symfem

extra:
  recipe-maintainers:
    - mscroggs
